import { GetSession } from "@/actions/GetSession";
import { CartTotal } from "@/actions/CartTotal";
import Footer from "@/components/Footer/Footer";
import { Montserrat } from "next/font/google";
import Nav from "@/components/Nav/Nav";
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/provider/Provider";

const font = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cartinate",
  description: "Generated by create next app",
};

type TotalType =
  | {
      price: number;
      quantity: number;
    }
  | undefined;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: any = await GetSession();
  const total: TotalType = await CartTotal(session?.id);

  return (
    <Providers>
      <html lang="en">
        <body className={font.className}>
          <Nav session={session} total={total} />
          <div className="">{children}</div>
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
